# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - dir: go
    main: v1beta1/main/main.go
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - image_templates:
      - "ghcr.io/rode/grafeas-elasticsearch:latest"
      - "ghcr.io/rode/grafeas-elasticsearch:{{ .Tag }}"
      - "ghcr.io/rode/grafeas-elasticsearch:v{{ .Major }}"
      - "ghcr.io/rode/grafeas-elasticsearch:v{{ .Major }}.{{ .Minor }}"
    extra_files:
      - "go.mod"
      - "go.sum"
      - "go"
      - "mappings"
