version: "3"
services:
  server:
    build:
      dockerfile: "./Dockerfile"
      context: "."
    ports:
      - "8080:8080"
    volumes:
      - ./local/docker-config.yaml:/etc/grafeas/config.yaml
    command: "--config /etc/grafeas/config.yaml"
    depends_on:
      elasticsearch:
        condition: service_healthy
  elasticsearch:
    build: "./local/elasticsearch"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    mem_limit: 1GB
    healthcheck:
      test: ["CMD", "curl", "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 1m
      retries: 3
  kibana:
    image: bitnami/kibana:7.9.3
    ports:
    - 5601:5601
    environment:
      - KIBANA_ELASTICSEARCH_URL=elasticsearch
    depends_on:
      - elasticsearch
