version: "3"
services:
  server:
    build: "./"
    ports:
      - "8080:8080"
    command: sh -c './wait-for.sh db:9200 -t 30 -- /grafeas-server'
    depends_on:
      - db
  db:
    build: "elasticsearch"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    mem_limit: 1GB