version: "3"
services:
  server:
    build: "./"
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    build: "elasticsearch"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

    ulimits:
      memlock:
        soft: -1
        hard: -1
