name: test
on: push

jobs:
  check:
    runs-on: ubuntu-latest
    container: golang:1.15
    steps:
      - uses: actions/checkout@v2

      - name: Download dependencies
        run: go mod tidy

      - name: Run unit tests
        run: |
          make test
          bash -c '/bin/bash <(curl -s https://codecov.io/bash)'

      - name: Build executable
        run: go build -v ./...

  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start services
        run: docker-compose up -d --build elasticsearch server
      - name: Run integration tests
        run: make integration
      - name: Teardown services
        if: ${{ always() }}
        run : docker-compose down
